# Generated by Django 3.1.5 on 2021-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'published'), ('DRAFT', 'draft')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
